//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SQAEntities : DbContext
    {
        public SQAEntities()
            : base("name=SQAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblProducts> tblProducts { get; set; }
        public virtual DbSet<tbminhchung> tbminhchung { get; set; }
        public virtual DbSet<tbminhchungchitiet> tbminhchungchitiet { get; set; }
        public virtual DbSet<tbtieuchi> tbtieuchi { get; set; }
        public virtual DbSet<tbtieuchuan> tbtieuchuan { get; set; }
        public virtual DbSet<tbvanbantheodonvi> tbvanbantheodonvi { get; set; }
        public virtual DbSet<tbvanbantheolinhvuc> tbvanbantheolinhvuc { get; set; }
        public virtual DbSet<tbvanban_kehoach> tbvanban_kehoach { get; set; }
        public virtual DbSet<tbctdt> tbctdt { get; set; }
        public virtual DbSet<tbnamhoc> tbnamhoc { get; set; }
        public virtual DbSet<tbphongban> tbphongban { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
