//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbctdt
    {
        public int id { get; set; }
        public string mactdt { get; set; }
        public string tenctdt { get; set; }
        public string khoaquanly { get; set; }
        public string filectdt { get; set; }
        public string ghichu { get; set; }
    }
}
