//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbtieuchi
    {
        public int id { get; set; }
        public Nullable<int> tieuchuan { get; set; }
        public Nullable<int> sotieuchi { get; set; }
        public string tentieuchi { get; set; }
    }
}
