//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbvanban_kehoach
    {
        public int id { get; set; }
        public Nullable<int> loaivanban { get; set; }
        public string sovanban { get; set; }
        public string tenvanban { get; set; }
        public string noibanhanh { get; set; }
        public string nguoinhap { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
        public string ghihu { get; set; }
        public string file_vanban { get; set; }
    }
}
