//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbvanbantheolinhvuc
    {
        public int id { get; set; }
        public string tenvanban { get; set; }
        public string soquyetdinh { get; set; }
        public string noibanhanh { get; set; }
        public string mota { get; set; }
        public string fileattach1 { get; set; }
        public string fileattach2 { get; set; }
    }
}
