//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tbvanbantheodonvi
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Xin vui lòng nhập tên văn bản"), MaxLength(4000, ErrorMessage = "Tên văn bản không dài hơn 4000 ký tự"), DisplayName("Tên văn bản")]
        public string tenvanban { get; set; }

        [MaxLength(1000, ErrorMessage = "Số văn bản không dài hơn 1000 ký tự"), DisplayName("Số quyết định")]
        public string soquyetdinh { get; set; }

        [Required(ErrorMessage = "Xin vui lòng nhập nơi ban hành văn bản"), MaxLength(4000, ErrorMessage = "Nơi ban hành không dài hơn 4000 ký tự"), DisplayName("Nơi ban hành")]
        public string noibanhanh { get; set; }

        [Required(ErrorMessage = "Xin vui lòng nhập tên nội dung trích yếu cho văn bản"), MaxLength(4000, ErrorMessage = "Nội dung trích yếu văn bản không dài hơn 4000 ký tự"), DisplayName("Mô tả"), DataType(DataType.MultilineText)]
        public string mota { get; set; }

        [MaxLength(1000, ErrorMessage = "Tên file không dài hơn 1000 ký tự"), DisplayName("File1")]
        public string fileattach1 { get; set; }

        [MaxLength(1000, ErrorMessage = "Tên file không dài hơn 1000 ký tự"), DisplayName("File2")]
        public string fileattach2 { get; set; }

        public Nullable<int> maphongban { get; set; }
    
        public virtual tbphongban tbphongban { get; set; }
    }
}
